/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        "text": string;
    }
    interface DsModal {
        "actions": any;
        "open": boolean;
        "title": string;
    }
    interface RootComponent {
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsModalElement extends Components.DsModal, HTMLStencilElement {
    }
    var HTMLDsModalElement: {
        prototype: HTMLDsModalElement;
        new (): HTMLDsModalElement;
    };
    interface HTMLRootComponentElement extends Components.RootComponent, HTMLStencilElement {
    }
    var HTMLRootComponentElement: {
        prototype: HTMLRootComponentElement;
        new (): HTMLRootComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-modal": HTMLDsModalElement;
        "root-component": HTMLRootComponentElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        "onButtonClick"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface DsModal {
        "actions"?: any;
        "open"?: boolean;
        "title"?: string;
    }
    interface RootComponent {
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-modal": DsModal;
        "root-component": RootComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-modal": LocalJSX.DsModal & JSXBase.HTMLAttributes<HTMLDsModalElement>;
            "root-component": LocalJSX.RootComponent & JSXBase.HTMLAttributes<HTMLRootComponentElement>;
        }
    }
}
